[
    { "name": "rocket", "char": "🚀" },
    { "name": "pizza", "char": "🍕" },
    { "name": "birthday cake", "char": "🎂" },
    { "name": "thumbs up", "char": "👍" },
    { "name": "thumbs down", "char": "👎" },
    { "name": "fire", "char": "🔥" },
    { "name": "rainbow", "char": "🌈" },
    { "name": "sunflower", "char": "🌻" },
    { "name": "taco", "char": "🌮" },
    { "name": "unicorn", "char": "🦄" },
    { "name": "ice cream", "char": "🍦" },
    { "name": "sushi", "char": "🍣" },
    { "name": "doughnut", "char": "🍩" },
    { "name": "camera", "char": "📷" },
    { "name": "guitar", "char": "🎸" },
    { "name": "microphone", "char": "🎤" },
    { "name": "paintbrush", "char": "🖌️" },
    { "name": "basketball", "char": "🏀" },
    { "name": "globe", "char": "🌍" },
    { "name": "train", "char": "🚆" },
    { "name": "bicycle", "char": "🚲" },
    { "name": "saxophone", "char": "🎷" },
    { "name": "teddy bear", "char": "🧸" },
    { "name": "laptop", "char": "💻" },
    { "name": "telephone", "char": "☎️" },
    { "name": "briefcase", "char": "💼" },
    { "name": "clock", "char": "🕰️" },
    { "name": "umbrella", "char": "☂️" },
    { "name": "watch", "char": "⌚" }
]
